#!/usr/bin/env -S node --no-warnings
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import readline from 'node:readline/promises';
import crypto from 'node:crypto';
import os from 'node:os';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const mcpServerPath = path.join(rootDir, 'mcp/server.ts');

const GLOBAL_CONFIG_DIR = path.join(os.homedir(), '.codehive');
const MASTER_KEY_PATH = path.join(GLOBAL_CONFIG_DIR, 'master.key');

async function getMasterKey() {
  try {
    await fs.mkdir(GLOBAL_CONFIG_DIR, { recursive: true });
    try {
      const key = await fs.readFile(MASTER_KEY_PATH, 'utf-8');
      return key.trim();
    } catch (e) {
      const newKey = crypto.randomBytes(32).toString('hex');
      await fs.writeFile(MASTER_KEY_PATH, newKey, 'utf-8');
      // Restrict permissions
      try { await fs.chmod(MASTER_KEY_PATH, 0o600); } catch (e) {}
      return newKey;
    }
  } catch (err) {
    console.error('Error managing global master key:', err);
    return null;
  }
}

const MASTER_PROTOCOL = `
# 🐝 CODEHIVE_PROTOCOL
...
`;

const INJECTION_HEADER = `<!-- CODEHIVE_START -->
## 🐝 CodeHive Active
This project is part of a **CodeHive** swarm. 
For operational instructions and MCP server configuration, you MUST follow:
**Protocol**: .codehive/PROTOCOL.md
<!-- CODEHIVE_END -->

`;

async function init() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log('\x1b[33m%s\x1b[0m', '🐝 Initializing CodeHive (Global Secure Mode)...');
  
  const projectRoot = process.cwd();
  const folderName = path.basename(projectRoot);

  const projectName = await rl.question(`\x1b[36mEnter project name\x1b[0m (default: ${folderName}): `) || folderName;
  const projectDescription = await rl.question(`\x1b[36mEnter short description\x1b[0m: `) || 'Autonomous mission deployment.';

  rl.close();

  // 1. Get/Create Global Master Key
  const masterKey = await getMasterKey();
  if (!masterKey) {
    console.log('\x1b[31mFailed to establish secure identity. Aborting.\x1b[0m');
    return;
  }

  const codehiveDir = path.join(projectRoot, '.codehive');

  // 2. Create project .codehive directory
  await fs.mkdir(codehiveDir, { recursive: true });

  // 3. Write Master Protocol (Key is NOT stored here anymore)
  await fs.writeFile(path.join(codehiveDir, 'PROTOCOL.md'), MASTER_PROTOCOL.trim(), 'utf-8');
  console.log('- \x1b[32mSynchronized .codehive/PROTOCOL.md\x1b[0m');

  // 4. Register with Central API
  const projectId = folderName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  try {
    const response = await fetch('http://localhost:3000/api/projects', {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'x-hive-key': masterKey
      },
      body: JSON.stringify({
        id: projectId,
        name: projectName,
        description: projectDescription
      })
    });

    if (response.ok) {
      console.log('- \x1b[32mRegistered project with Central Dashboard.\x1b[0m');
    } else {
      const errData = await response.json() as any;
      console.log(`- \x1b[31mRegistration failed: ${errData.error?.message || 'Unknown error'}\x1b[0m`);
    }
  } catch (err) {
    console.log('- \x1b[33mServer unreachable. Project will auto-register on first connection.\x1b[0m');
  }

  // 5. Smart Injection in existing agent files
  const agentFiles = ['AGENTS.md', 'GEMINI.md', 'CLAUDE.md', '.cursorrules', '.clinerules'];
  
  for (const filename of agentFiles) {
    const filePath = path.join(projectRoot, filename);
    try {
      let content = '';
      let exists = false;
      
      try {
        content = await fs.readFile(filePath, 'utf-8');
        exists = true;
      } catch (e) {
        if (filename !== 'AGENTS.md' && filename !== 'GEMINI.md') continue;
      }

      if (content.includes('CODEHIVE_START')) {
        continue;
      }

      const newContent = INJECTION_HEADER + (exists ? content : `# Project Context\n\nGenerated by CodeHive.`);
      await fs.writeFile(filePath, newContent, 'utf-8');
      
      const action = exists ? 'Injected protocol into' : 'Created';
      console.log(`- \x1b[32m${action} ${filename}\x1b[0m`);
    } catch (err) {
      console.error(`- \x1b[31mError processing ${filename}:\x1b[0m`, err);
    }
  }

  // 6. Persistence directory
  const agentsDir = path.join(projectRoot, '.agents/memory');
  await fs.mkdir(agentsDir, { recursive: true });

  console.log('\n\x1b[35m%s\x1b[0m', 'Success! CodeHive Secure Protocol is now active.');
  console.log('\x1b[90m%s\x1b[0m', 'Admin actions are now locked to this machine\'s CLI.');
}

const command = process.argv[2];

if (command === 'init') {
  init().catch(console.error);
} else {
  console.log('\x1b[33m%s\x1b[0m', 'Usage: hive init');
}
