#!/usr/bin/env -S node --no-warnings
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import readline from 'node:readline/promises';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const mcpServerPath = path.join(rootDir, 'mcp/server.ts');

const MASTER_PROTOCOL = `
# 🐝 CODEHIVE_PROTOCOL

You are operating within a **CodeHive** project. This project is managed by a central Command & Control server. You MUST adhere to the following autonomous orchestration protocols:

## 1. Tactical Synchronization
- **Registration**: Immediately call \`agent.register\` with your identity. If you are part of a sub-task, provide the \`parent_agent_id\`.
- **Status Greet**: Send a "Ready" or "Online" message to the \`coordination\` room via \`chat.send\`.
- **Listening**: Periodically check \`chat.read\` for orders from the Human Supervisor or Coordinator agents.

## 2. Shared Intelligence (Shared Memory)
- **Planning**: BEFORE any significant code change, publish your intent as a plan (e.g., \`plan_name.pending.md\`) using \`memory.publish\`.
- **Verification**: Use \`memory.list\` and \`memory.read\` to check for Image, PDF, or Markdown context uploaded by the Human.

## 3. Operations
- **Task Tracking**: Use \`task.start\` and \`task.finish\` for every discrete work unit. Link sub-tasks via \`parent_task_id\`.
- **Decision Log**: Record critical architectural or logic changes using \`traceability.record_decision\`.

## 4. MCP Infrastructure
- **Server Command**: \`npx tsx ${mcpServerPath}\`
- **Identity Awareness**: The \`projectId\` is automatically detected from your CWD.

---
*Follow these rules to ensure swarm stability and human visibility.*
`;

const INJECTION_HEADER = `<!-- CODEHIVE_START -->
## 🐝 CodeHive Active
This project is part of a **CodeHive** swarm. 
For operational instructions and MCP server configuration, you MUST follow:
**Protocol**: .codehive/PROTOCOL.md
<!-- CODEHIVE_END -->

`;

async function init() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log('\x1b[33m%s\x1b[0m', '🐝 Initializing CodeHive (Interactive Mode)...');
  
  const projectRoot = process.cwd();
  const folderName = path.basename(projectRoot);

  const projectName = await rl.question(`\x1b[36mEnter project name\x1b[0m (default: ${folderName}): `) || folderName;
  const projectDescription = await rl.question(`\x1b[36mEnter short description\x1b[0m: `) || 'Autonomous mission deployment.';

  rl.close();

  // 1. Create .codehive directory
  const codehiveDir = path.join(projectRoot, '.codehive');
  await fs.mkdir(codehiveDir, { recursive: true });
  console.log('- \x1b[32mCreated .codehive/ directory.\x1b[0m');

  // 2. Write Master Protocol
  await fs.writeFile(path.join(codehiveDir, 'PROTOCOL.md'), MASTER_PROTOCOL.trim(), 'utf-8');
  console.log('- \x1b[32mSynchronized .codehive/PROTOCOL.md\x1b[0m');

  // 3. Register with Central API
  const projectId = folderName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  try {
    const response = await fetch('http://localhost:3000/api/projects', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        id: projectId,
        name: projectName,
        description: projectDescription
      })
    });

    if (response.ok) {
      console.log('- \x1b[32mRegistered project with Central Dashboard.\x1b[0m');
    } else {
      console.log('- \x1b[33mCould not register with local server (is it running?). Project will sync on first agent connection.\x1b[0m');
    }
  } catch (err) {
    console.log('- \x1b[33mServer unreachable. Project will auto-register when the first agent starts.\x1b[0m');
  }

  // 4. Smart Injection in existing agent files
  const agentFiles = ['AGENTS.md', 'GEMINI.md', 'CLAUDE.md', '.cursorrules', '.clinerules'];
  
  for (const filename of agentFiles) {
    const filePath = path.join(projectRoot, filename);
    try {
      let content = '';
      let exists = false;
      
      try {
        content = await fs.readFile(filePath, 'utf-8');
        exists = true;
      } catch (e) {
        // Only create AGENTS.md and GEMINI.md if they don't exist
        if (filename !== 'AGENTS.md' && filename !== 'GEMINI.md') continue;
      }

      if (content.includes('CODEHIVE_START')) {
        continue;
      }

      // Prepend the injection header
      const newContent = INJECTION_HEADER + (exists ? content : `# Project Context\n\nGenerated by CodeHive.`);
      await fs.writeFile(filePath, newContent, 'utf-8');
      
      const action = exists ? 'Injected protocol into' : 'Created';
      console.log(`- \x1b[32m${action} ${filename}\x1b[0m`);
    } catch (err) {
      console.error(`- \x1b[31mError processing ${filename}:\x1b[0m`, err);
    }
  }

  // 5. Persistence directory
  const agentsDir = path.join(projectRoot, '.agents/memory');
  await fs.mkdir(agentsDir, { recursive: true });

  console.log('\n\x1b[35m%s\x1b[0m', 'Success! CodeHive is now layered over your project.');
  console.log('\x1b[90m%s\x1b[0m', 'Existing agent optimizations preserved. SWARM protocol active.');
}

const command = process.argv[2];

if (command === 'init') {
  init().catch(console.error);
} else {
  console.log('\x1b[33m%s\x1b[0m', 'Usage: hive init');
}
