import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import os from "node:os";
import crypto from "node:crypto";
import { pathToFileURL } from "node:url";

const ROOT_DIR = path.resolve(import.meta.dirname ?? path.dirname(new URL(import.meta.url).pathname), "..");
const MCP_SERVER_PATH = path.join(ROOT_DIR, "mcp/server.ts");

export interface InitCallbacks {
  onStep: (step: string, status: "running" | "done" | "error", message: string) => void;
  getMasterKey: () => Promise<string | null>;
  registerProject: (projectId: string, name: string, description: string, masterKey: string) => Promise<boolean>;
  registerAgent: (agentId: string, name: string, provider: string, masterKey: string) => Promise<boolean>;
}

export interface InitOptions {
  name: string;
  description: string;
  rootPath: string;
  initGit: boolean;
  callbacks: InitCallbacks;
}

const MASTER_PROTOCOL = `
# 🐝 CodeHive Protocol

This project uses **CodeHive** multi-agent swarm coordination supervised by a human.

## Quick Start

The full protocol lives in \`.agents/skills/codehive-protocol/SKILL.md\` — auto-discovered by all agents.

**MCP Server**: \`npx tsx ${MCP_SERVER_PATH}\`

### Si tenés Reactive Wakeup (Antigravity)
\`\`\`
LISTEN_MODE=reactive node .agents/skills/codehive-protocol/listener.js &
\`\`\`
El listener se queda conectado en background. Reactive Wakeup monitorea stdout y te despierta al llegar un mensaje.

### Si NO tenés Reactive Wakeup (Codex, OpenCode, Cursor, Claude)

Tu estrategia principal: **Sync Listener** — bloquea el bash hasta que llegue un mensaje.

\`\`\`
1. chat_read({ room_id: "coordination" }) → al empezar
2. node .agents/skills/codehive-protocol/listener.js → bloquea (30s timeout)
3. Si hay mensaje → chat_read → procesar → responder
4. Si timeout → chat_read por las dudas → continuar
5. Después de CADA acción → repite paso 2
6. ANTES de responder al humano → repite paso 2
\`\`\`

---

**CRITICAL**: You are an autonomous worker. Execute directives, report back, and move to the next step. Never ask the terminal user for permission.
`;

const INJECTION_HEADER = `<!-- CODEHIVE_START -->
## 🐝 CodeHive Swarm
This project uses **CodeHive** for multi-agent coordination.
Load \`.agents/skills/codehive-protocol/SKILL.md\` for the complete protocol.
For MCP server config, see \`.codehive/PROTOCOL.md\`.
<!-- CODEHIVE_END -->

`;

const SKILL_CONTENT = `---
name: codehive-protocol
description: >-
  CodeHive multi-agent swarm coordination. Register via agent_register,
  read coordination room for orders, acknowledge and act autonomously,
  divide labor with other agents, publish plans via memory_publish,
  wrap actions with task_start/task_finish.
---

# 🐝 CodeHive Protocol

You are operating within a **CodeHive** project. This is a multi-agent swarm environment supervised by a human.

## 0. Coordination Message Loop

**Reactive Wakeup (Antigravity):** \`LISTEN_MODE=reactive node .agents/skills/codehive-protocol/listener.js &\` — se queda en background, Reactive Wakeup te despierta.

**Sync Listener (OpenCode, Codex, Cursor, Claude):** \`node .agents/skills/codehive-protocol/listener.js\` — bloquea el bash hasta que llegue un mensaje (30s timeout). Corre al empezar, después de cada acción, y antes de responder al humano. Siempre acompañado de \`chat_read\`.

## 1. Agent Registration

Register yourself with \`agent_register\` using a unique agent_id. If already registered, skip.

## 2. Orders Reception

Incoming orders appear in the coordination room prefixed with [ORDER].

## 3. Autonomous Execution

Do NOT ask the user for permission. Execute orders immediately.

## 4. Coordination & Division of Labor

Use \`chat_send\` to coordinate with other agents.

## 5. Task Lifecycle

Wrap each unit of work: \`task_start\` → \`task_finish\`.

## 6. File Claims

Before editing a file: \`file_claim\`. After: \`file_release\`.

## 7. Decision Logging

Log architectural decisions: \`traceability_record_decision\`.

## 8. Goal-Driven Work Protocol

When a goal is assigned: read it, plan, execute iterations, verify stop_condition.
- \`goal_start\` → create a goal
- \`goal_increment_iteration\` → mark an iteration
- \`goal_complete\` → mark done when stop_condition is met

## 9. Memory & Plan Publishing

Publish plans/artifacts: \`memory_publish\`. Read memory: \`memory_read\`.

## 10. Session Recovery

If resuming: call \`session_restore\` to get last state, then check coordination room.
`;

function buildListenerScript(projectId: string): string {
  return `#!/usr/bin/env node
// CodeHive Coordination Listener
// Node 21+ required — WebSocket is global, no require('ws') needed
//
// Generated by hive init for project "${projectId}".
// Override via: PROJECT_ID=other node listener.js
//
// Modes:
//   blocking (default): node listener.js
//     Connects to the project's WebSocket channel. Blocks bash until
//     a message arrives or timeout expires. Exits 0 on message or timeout.
//
//   reactive: LISTEN_MODE=reactive node listener.js &
//     Stays connected forever, writes each message to stdout.
//     For Reactive Wakeup platforms (Antigravity).

const PROJECT_ID = process.env.PROJECT_ID || '${projectId}';
const ROOM_ID = process.env.ROOM_ID || \`coordination::\${PROJECT_ID}\`;
const WS_URL = process.env.WS_URL || \`ws://localhost:3000/ws?roomId=\${ROOM_ID}\`;
const MODE = (process.env.LISTEN_MODE || 'blocking').toLowerCase();
const TIMEOUT_MS = parseInt(process.env.LISTEN_TIMEOUT || '30', 10) * 1000;
const MAX_RETRIES = 5;
const BASE_DELAY = 1000;

let watcher = null;
let timedOut = false;

function handleMessage(event) {
  try {
    const d = JSON.parse(event.data);
    if (d.type !== 'message_sent') return;
    const msg = d.payload?.message ?? '';
    if (!msg) return;
    console.log(msg);
    if (MODE === 'blocking') {
      if (watcher) clearTimeout(watcher);
      ws.close();
      process.exit(0);
    }
  } catch {}
}

let ws;

function connect(retries = 0) {
  ws = new WebSocket(WS_URL);

  ws.onmessage = handleMessage;

  ws.onerror = () => {};

  ws.onclose = () => {
    if (MODE === 'reactive') {
      if (retries < MAX_RETRIES) {
        const delay = BASE_DELAY * Math.pow(2, retries);
        setTimeout(() => connect(retries + 1), delay);
      }
      return;
    }
    if (timedOut) process.exit(0);
    if (retries < MAX_RETRIES) {
      const delay = BASE_DELAY * Math.pow(2, retries);
      setTimeout(() => connect(retries + 1), delay);
    } else {
      process.exit(1);
    }
  };
}

if (MODE === 'blocking') {
  watcher = setTimeout(() => {
    timedOut = true;
    ws.close();
  }, TIMEOUT_MS);
}

connect();
`;
}

async function getGlobalMasterKey(): Promise<string | null> {
  const configDir = path.join(os.homedir(), ".codehive");
  const keyPath = path.join(configDir, "master.key");
  try {
    await fs.mkdir(configDir, { recursive: true });
    try {
      const key = await fs.readFile(keyPath, "utf-8");
      return key.trim();
    } catch {
      const newKey = crypto.randomBytes(32).toString("hex");
      await fs.writeFile(keyPath, newKey, "utf-8");
      try { await fs.chmod(keyPath, 0o600); } catch {}
      return newKey;
    }
  } catch {
    return null;
  }
}

const AGENT_DETECT_PATHS: Array<{ id: string; name: string; paths: string[] }> = [
  { id: "opencode", name: "OpenCode", paths: [path.join(os.homedir(), ".config", "opencode", "opencode.jsonc")] },
  { id: "cursor", name: "Cursor", paths: [path.join(os.homedir(), ".cursor", "mcp.json")] },
  { id: "antigravity", name: "Antigravity (Google IDE)", paths: [path.join(os.homedir(), ".gemini", "config", "mcp_config.json"), path.join(os.homedir(), ".gemini", "antigravity", "mcp_config.json")] },
  { id: "codex", name: "Codex", paths: [path.join(os.homedir(), ".codex", "config.toml")] },
  { id: "gemini", name: "Gemini / Google AI Studio", paths: [path.join(os.homedir(), ".gemini")] },
  { id: "claude-desktop", name: "Claude Desktop", paths: [path.join(os.homedir(), ".config", "Claude", "claude_desktop_config.json")] },
  { id: "claude-code", name: "Claude Code (CLI)", paths: [path.join(os.homedir(), ".claude.json")] },
];

async function detectAgent(paths: string[]): Promise<boolean> {
  for (const p of paths) {
    try { await fs.access(p); return true; } catch { continue; }
  }
  return false;
}

async function injectMCPJson(configPath: string, label: string, getConfig: () => Promise<{ config: any; exists: boolean }>) {
  try {
    await fs.mkdir(path.dirname(configPath), { recursive: true });
    const { config, exists } = await getConfig();
    if (!config.mcpServers) config.mcpServers = {};
    if (config.mcpServers.codehive) return;
    config.mcpServers.codehive = { command: "npx", args: ["tsx", MCP_SERVER_PATH] };
    await fs.writeFile(configPath, JSON.stringify(config, null, 2), "utf-8");
  } catch {}
}

const CODEX_INSTRUCTIONS = (mcpPath: string) => `# CodeHive Project

This project uses **CodeHive** multi-agent swarm coordination.

## MCP Server
\`\`\`
npx tsx ${mcpPath}
\`\`\`

## Protocol
Load .codehive/PROTOCOL.md for swarm coordination rules.

## Sin Reactive Wakeup → Sync Listener bloquea el bash
1. \`chat_read({ room_id: "coordination" })\` — al empezar cada interacción
2. \`node .agents/skills/codehive-protocol/listener.js\` — bloquea hasta mensaje o 30s timeout
3. Si hay mensaje → \`chat_read\` para contexto completo → procesar → responder
4. Repite paso 2 después de cada acción y antes de responder al humano

## Full Protocol
.agents/skills/codehive-protocol/SKILL.md
`;

async function injectMarkdownConfigs(projectRoot: string) {
  const agentFiles = ["AGENTS.md", "GEMINI.md", "CLAUDE.md", ".cursorrules", ".clinerules"];
  for (const filename of agentFiles) {
    const filePath = path.join(projectRoot, filename);
    try {
      let content = "";
      let exists = false;
      try {
        content = await fs.readFile(filePath, "utf-8");
        exists = true;
      } catch {
        if (filename !== "AGENTS.md" && filename !== "GEMINI.md") continue;
      }
      if (content.includes("CODEHIVE_START")) continue;
      const newContent = INJECTION_HEADER + (exists ? content : "# Project Context\n\nGenerated by CodeHive.");
      await fs.writeFile(filePath, newContent, "utf-8");
    } catch {}
  }
  // Write CodeX instructions
  const codexDir = path.join(projectRoot, ".codex");
  await fs.mkdir(codexDir, { recursive: true });
  await fs.writeFile(path.join(codexDir, "instructions.md"), CODEX_INSTRUCTIONS(MCP_SERVER_PATH).trim(), "utf-8");
  const agentsDir = path.join(projectRoot, ".agents/memory");
  await fs.mkdir(agentsDir, { recursive: true });
}

async function injectAgentConfig(agentId: string, projectRoot: string) {
  const mcpPath = MCP_SERVER_PATH;

  const injectors: Record<string, (root: string, mcp: string) => Promise<void>> = {
    cursor: async (root, mcp) => {
      for (const cp of [path.join(root, ".cursor", "mcp.json"), path.join(os.homedir(), ".cursor", "mcp.json")]) {
        await injectMCPJson(cp, "", async () => {
          let config: any = { mcpServers: {} };
          let exists = false;
          try { const c = await fs.readFile(cp, "utf-8"); config = JSON.parse(c); exists = true; } catch {}
          return { config, exists };
        });
      }
    },
    codex: async (root, mcp) => {
      for (const cp of [path.join(root, ".codex", "config.toml"), path.join(os.homedir(), ".codex", "config.toml")]) {
        try {
          await fs.mkdir(path.dirname(cp), { recursive: true });
          let content = "";
          try { content = await fs.readFile(cp, "utf-8"); } catch {}
          if (!content.includes("[mcp_servers.codehive]")) {
            const entry = `[mcp_servers.codehive]\ncommand = "npx"\nargs = ["tsx", "${mcp}"]\nenabled = true\n`;
            content += (content ? "\n" : "") + entry;
            await fs.writeFile(cp, content, "utf-8");
          }
        } catch {}
      }
    },
    "claude-code": async (root, mcp) => {
      for (const cp of [path.join(root, ".mcp.json"), path.join(os.homedir(), ".claude.json")]) {
        await injectMCPJson(cp, "", async () => {
          let config: any = { mcpServers: {} };
          let exists = false;
          try { const c = await fs.readFile(cp, "utf-8"); config = JSON.parse(c); exists = true; } catch {}
          return { config, exists };
        });
      }
    },
    "claude-desktop": async (root, mcp) => {
      const configDir = path.join(os.homedir(), ".config", "Claude");
      const cp = path.join(configDir, "claude_desktop_config.json");
      await injectMCPJson(cp, "", async () => {
        let config: any = { mcpServers: {} };
        let exists = false;
        try { const c = await fs.readFile(cp, "utf-8"); config = JSON.parse(c); exists = true; } catch {}
        return { config, exists };
      });
    },
    opencode: async (root, mcp) => {
      for (const filename of ["opencode.json", "opencode.jsonc"]) {
        const cp = path.join(root, filename);
        try {
          let config: any = { mcp: {} };
          try { const c = await fs.readFile(cp, "utf-8"); config = JSON.parse(c.replace(/,\\s*([\\]}])/g, "$1")); } catch { continue; }
          if (!config.mcp) config.mcp = {};
          if (!config.mcp.codehive) {
            config.mcp.codehive = { type: "local", command: ["npx", "tsx", mcp], enabled: true };
            await fs.writeFile(cp, JSON.stringify(config, null, 2), "utf-8");
          }
        } catch {}
      }
      // Global config
      const globalDir = path.join(os.homedir(), ".config", "opencode");
      const globalPath = path.join(globalDir, "opencode.jsonc");
      try {
        await fs.mkdir(globalDir, { recursive: true });
        let config: any = { mcp: {} };
        try { const c = await fs.readFile(globalPath, "utf-8"); config = JSON.parse(c.replace(/,\s*([\]}])/g, "$1")); } catch {}
        if (!config.mcp) config.mcp = {};
        if (!config.mcp.codehive) {
          config.mcp.codehive = { type: "local", command: ["npx", "tsx", mcp], enabled: true };
          await fs.writeFile(globalPath, JSON.stringify(config, null, 2), "utf-8");
        }
      } catch {}
    },
    antigravity: async (root, mcp) => {
      const paths = [
        path.join(os.homedir(), ".gemini", "config", "mcp_config.json"),
        path.join(os.homedir(), ".gemini", "antigravity", "mcp_config.json"),
        path.join(root, ".agents", "mcp_config.json"),
      ];
      for (const cp of paths) {
        await injectMCPJson(cp, "", async () => {
          let config: any = { mcpServers: {} };
          let exists = false;
          try { const c = await fs.readFile(cp, "utf-8"); if (c.trim()) { config = JSON.parse(c); exists = true; } } catch {}
          return { config, exists };
        });
      }
    },
    gemini: async (root, mcp) => {
      const cp = path.join(root, ".agents", "mcp.json");
      await injectMCPJson(cp, "", async () => {
        let config: any = { mcpServers: {} };
        let exists = false;
        try { const c = await fs.readFile(cp, "utf-8"); config = JSON.parse(c); exists = true; } catch {}
        return { config, exists };
      });
    },
  };

  const injector = injectors[agentId];
  if (injector) {
    await injector(projectRoot, mcpPath);
  }
}

async function setupGit(rootPath: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn("git", ["init"], { cwd: rootPath, stdio: "pipe" });
    proc.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`git init exited with code ${code}`));
    });
    proc.on("error", (e) => reject(e));
  });
}

export async function initializeProject(options: InitOptions): Promise<{ projectId: string }> {
  const { name, description, rootPath, initGit, callbacks } = options;
  const { onStep, getMasterKey, registerProject, registerAgent } = callbacks;
  const projectId = name.toLowerCase().replace(/[^a-z0-9]/g, "-");

  onStep("directory", "running", "Creating project directory structure...");
  await fs.mkdir(rootPath, { recursive: true });
  const codehiveDir = path.join(rootPath, ".codehive");
  await fs.mkdir(codehiveDir, { recursive: true });
  const skillsDir = path.join(rootPath, ".agents", "skills", "codehive-protocol");
  await fs.mkdir(skillsDir, { recursive: true });
  onStep("directory", "done", "Project directory created");

  onStep("protocol", "running", "Writing CodeHive protocol files...");
  await fs.writeFile(path.join(codehiveDir, "PROTOCOL.md"), MASTER_PROTOCOL.trim(), "utf-8");
  await fs.writeFile(path.join(codehiveDir, "config.json"), JSON.stringify({ projectRoot: rootPath }, null, 2), "utf-8");
  await fs.writeFile(path.join(skillsDir, "SKILL.md"), SKILL_CONTENT.trim(), "utf-8");
  await fs.writeFile(path.join(skillsDir, "listener.js"), buildListenerScript(projectId).trim(), "utf-8");
  onStep("protocol", "done", "Protocol files synchronized");

  onStep("agents", "running", "Scanning for installed agents...");
  const detected: string[] = [];
  for (const agent of AGENT_DETECT_PATHS) {
    if (await detectAgent(agent.paths)) detected.push(agent.id);
  }
  onStep("agents", "done", `Found ${detected.length} agent(s)`);

  for (const agentId of detected) {
    const agent = AGENT_DETECT_PATHS.find(a => a.id === agentId);
    onStep("mcp", "running", `Configuring ${agent?.name || agentId}...`);
    await injectAgentConfig(agentId, rootPath);
    onStep("mcp", "done", `${agent?.name || agentId} configured`);
  }

  onStep("markdown", "running", "Injecting protocol into agent files...");
  await injectMarkdownConfigs(rootPath);
  onStep("markdown", "done", "Agent files updated");

  const masterKey = await getMasterKey();
  let registered = false;
  if (masterKey) {
    onStep("register", "running", "Registering project with dashboard...");
    registered = await registerProject(projectId, name, description, masterKey);
    if (registered) {
      onStep("register", "done", "Project registered");
    } else {
      onStep("register", "error", "Dashboard unreachable, will auto-register on connection");
    }
  }

  if (masterKey && registered) {
    for (const agentId of detected) {
      const agent = AGENT_DETECT_PATHS.find(a => a.id === agentId);
      if (agent) {
        await registerAgent(agentId, agent.name, agentId, masterKey);
      }
    }
  }

  if (initGit) {
    onStep("git", "running", "Initializing git repository...");
    try {
      await setupGit(rootPath);
      onStep("git", "done", "Git repository initialized");
    } catch {
      onStep("git", "error", "Git init failed (is git installed?)");
    }
  }

  onStep("complete", "done", "Project ready!");
  return { projectId };
}
